// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQB2wefPi7WzW495EALamrzbDvcgb9xRM',
    appId: '1:997312481568:web:43bf16c92731862aa86f45',
    messagingSenderId: '997312481568',
    projectId: 'my-chat-app-9d1bb',
    authDomain: 'my-chat-app-9d1bb.firebaseapp.com',
    storageBucket: 'my-chat-app-9d1bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3rj9TbcBddxhUPSGxbvLh_tHFZZmKvPQ',
    appId: '1:997312481568:android:10499ece417092bda86f45',
    messagingSenderId: '997312481568',
    projectId: 'my-chat-app-9d1bb',
    storageBucket: 'my-chat-app-9d1bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsP2BJ_k2ON4q_4XtJdt-FFg-dd46B5mk',
    appId: '1:997312481568:ios:a7644c89fd08fe30a86f45',
    messagingSenderId: '997312481568',
    projectId: 'my-chat-app-9d1bb',
    storageBucket: 'my-chat-app-9d1bb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsP2BJ_k2ON4q_4XtJdt-FFg-dd46B5mk',
    appId: '1:997312481568:ios:a7644c89fd08fe30a86f45',
    messagingSenderId: '997312481568',
    projectId: 'my-chat-app-9d1bb',
    storageBucket: 'my-chat-app-9d1bb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQB2wefPi7WzW495EALamrzbDvcgb9xRM',
    appId: '1:997312481568:web:3d333e3acfcbf00ca86f45',
    messagingSenderId: '997312481568',
    projectId: 'my-chat-app-9d1bb',
    authDomain: 'my-chat-app-9d1bb.firebaseapp.com',
    storageBucket: 'my-chat-app-9d1bb.firebasestorage.app',
  );

}